// This file is generated

S_text_0 = [
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nGRO\n</p>",
"",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nUNSW Canberra\n</p><p>\n<b>\nAbbreviation: \n</b>\nAIF\n</p><p>\n<b>\nPublication information: \n</b>\nhttp://www.aif.adfa.edu.au/\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nThe Church of Jesus Christ of Latter-day Saints\n</p><p>\n<b>\nAbbreviation: \n</b>\nFHL\n</p>",
"",
"<p>\n<b>\nAbbreviation: \n</b>\nGRO Scotland\n</p>",
"",
"",
"",
"",
"<p>\n<b>\nAbbreviation: \n</b>\nIGI\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nFamilySearc\n</p><p>\n<b>\nPublication information: \n</b>\nhttps://familysearch.org/\n</p>",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nFindMyPast.co.uk\n</p>",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nAbbreviation: \n</b>\nLondon, England, Marriages and Banns, 1754-1921\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com\n</p>",
"",
"",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nNational Archives\n</p>",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nAbbreviation: \n</b>\nNorfolk Transcription Archive\n</p><p>\n<b>\nPublication information: \n</b>\nhttp://www.genealogy.doun.org/transcriptions/index.php\n</p>",
"",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nhttp://www.oldbaileyonline.org/\n</p>",
"<p>\n<b>\nPublication information: \n</b>\nhttp://pubshistory.com/LondonPubs/StDunstaninEast/QueensHead.shtml\n</p>",
"<p>\n<b>\nPublication information: \n</b>\nhttp://www.queensroyalsurreys.org.uk/monuments/cwgc/the_queens_ww2.rtf\n</p>",
"",
"",
"<p>\n<b>\nAuthor: \n</b>\nNational Records of Scotland\n</p><p>\n<b>\nPublication information: \n</b>\nhttp://www.scotlandspeople.gov.uk/\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nRay Long\n</p><p>\n<b>\nAbbreviation: \n</b>\nFoH\n</p><p>\n<b>\nPublication information: \n</b>\nhttp://fp.raylong.plus.com/hadleigh/\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nRay Long\n</p><p>\n<b>\nAbbreviation: \n</b>\nFoK\n</p><p>\n<b>\nPublication information: \n</b>\nhttp://fp.raylong.plus.com/kersey/index.html\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nFindMyPast.co.uk\n</p>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nPublication information: \n</b>\nhttp://vitaldb.moorlandit.com/\n</p>",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_S_text_0.js');
